name: Deploy Main Documentation

on:
  push:
    branches: [main]
    paths: ['docs/**', '.github/workflows/deploy-docs-main.yml']

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Honkit
        run: npm install -g honkit
        
      - name: Build documentation
        run: |
          cd docs
          honkit build . ../_book
          cp redirect.html ../_book/redirect.html
          
      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
          
      - name: Notify deployment success
        run: |
          echo "✅ Documentation successfully deployed to production!"
          echo "🌐 URL: https://your-docs-site.vercel.app"
          
      - name: Create deployment summary
        uses: actions/github-script@v7
        with:
          script: |
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'production'
            });
            
            if (deployments.length > 0) {
              const latestDeployment = deployments[0];
              console.log(`🚀 Latest deployment: ${latestDeployment.environment_url}`);
              console.log(`📅 Deployed at: ${latestDeployment.created_at}`);
            }
