name: Deploy Custom Pattern Documentation

on:
  push:
    branches:
      - 'custom/*'
      - 'special/*'
      - 'unique/*'
      - 'pattern/*'
      - 'format/*'
    paths: ['docs/**', '*.md']

jobs:
  deploy-custom-pattern:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Honkit
        run: npm install -g honkit
        
      - name: Build documentation
        run: |
          cd docs
          honkit build . ../_book
          cp redirect.html ../_book/redirect.html
          
      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--target=preview'
          
      - name: Create custom pattern summary
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'preview'
            });
            
            if (deployments.length > 0) {
              const latestDeployment = deployments[0];
              
              console.log(`🚀 Documentation deployed for custom pattern branch ${branch}`);
              console.log(`🌐 Preview URL: ${latestDeployment.environment_url}`);
              
              // Create a comment on the commit if it's a PR
              try {
                const { data: commits } = await github.rest.repos.listCommits({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  sha: context.sha
                });
                
                if (commits.length > 0) {
                  const commit = commits[0];
                  console.log(`📝 Commit: ${commit.commit.message}`);
                }
              } catch (error) {
                console.log('Could not fetch commit details');
              }
            }
          
      - name: Notify deployment success
        run: |
          echo "✅ Documentation successfully deployed for custom pattern branch ${{ github.ref_name }}!"
          echo "🎯 Custom Pattern: ${{ github.ref_name }}"
          echo "🌐 Preview URL: https://preview-your-docs-site.vercel.app"
          
      - name: Create custom pattern notification
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            
            // Create an issue to track the custom pattern
            try {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Custom Pattern Documentation: ${branch}`,
                body: `Documentation has been deployed for custom pattern branch \`${branch}\`.\n\n**Status:** Deployed to preview\n**Environment:** Preview\n**Branch:** ${branch}\n\n**Note:** This is a custom pattern branch.\n\nPlease review and merge when ready.`,
                labels: ['documentation', 'preview', 'custom-pattern']
              });
            } catch (error) {
              console.log('Could not create custom pattern issue');
            }
