name: Deploy Config Pattern Documentation

on:
  push:
    paths:
      - 'docs/**'
      - '*.md'
      - '*.markdown'
      - '*.txt'
      - '*.rst'
      - 'book.json'
      - 'SUMMARY.md'
      - 'vercel.json'
      - '.github/workflows/deploy-docs-*.yml'
    paths-ignore:
      - 'src/**'
      - 'tests/**'
      - 'vendor/**'
      - 'node_modules/**'

jobs:
  deploy-config-pattern:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Honkit
        run: npm install -g honkit
        
      - name: Build documentation
        run: |
          cd docs
          honkit build . ../_book
          cp redirect.html ../_book/redirect.html
          
      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--target=preview'
          
      - name: Create config pattern summary
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'preview'
            });
            
            if (deployments.length > 0) {
              const latestDeployment = deployments[0];
              
              console.log(`🚀 Documentation deployed for config pattern branch ${branch}`);
              console.log(`🌐 Preview URL: ${latestDeployment.environment_url}`);
              
              // Create a comment on the commit if it's a PR
              try {
                const { data: commits } = await github.rest.repos.listCommits({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  sha: context.sha
                });
                
                if (commits.length > 0) {
                  const commit = commits[0];
                  console.log(`📝 Commit: ${commit.commit.message}`);
                }
              } catch (error) {
                console.log('Could not fetch commit details');
              }
            }
          
      - name: Notify deployment success
        run: |
          echo "✅ Documentation successfully deployed for config pattern branch ${{ github.ref_name }}!"
          echo "⚙️ Config Pattern: ${{ github.ref_name }}"
          echo "🌐 Preview URL: https://preview-your-docs-site.vercel.app"
          
      - name: Create config pattern notification
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            
            // Create an issue to track the config pattern
            try {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Config Pattern Documentation: ${branch}`,
                body: `Documentation has been deployed for config pattern branch \`${branch}\`.\n\n**Status:** Deployed to preview\n**Environment:** Preview\n**Branch:** ${branch}\n\n**Note:** This deployment is based on configuration file changes.\n\nPlease review and merge when ready.`,
                labels: ['documentation', 'preview', 'config-pattern']
              });
            } catch (error) {
              console.log('Could not create config pattern issue');
            }
